# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-addtime'], 'verbose_name': '新闻', 'verbose_name_plural': '新闻'},
        ),
        migrations.AddField(
            model_name='test',
            name='topped',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
    ]
